# License: BSD 3 clause

# Tests for plot consist in checking the data inside axes generated by
# matplotlib
# http://stackoverflow.com/questions/27948126/how-can-i-write-unit-tests-against-code-that-uses-matplotlib
