
name: Build Tick on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TICK_DEBUG: 0


jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install swig
      run: |
        git clone https://github.com/swig/swig -b rel-4.0.2 swig
        cd swig && ./autogen.sh && ./configure --without-pcre
        make && sudo make install && cd .. && rm -rf swig

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        python3 -m pip install wheel pip --upgrade
        python3 -m pip install -r requirements.txt
        python3 -m pip install tensorflow-cpu
        python3 setup.py build_ext --inplace cpptest pytest
