
name: Build Tick on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TICK_DEBUG: 0
  TICK_WERROR: 0
  MKN_GCC_PREFERRED: 1

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.9', '3.10'] # '3.8' has "'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64





    - name: info
      run: |
        python3 -V
        gcc -v
        swig -version

    - name: pip
      run: |
        python3 -m pip install wheel pip --upgrade
        python3 -m pip install -r requirements.txt

    - name: build
      run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        PATH=$PWD:$PATH KLOG=3 ./sh/mkn.sh

    - name: cpptest
      run: |
        PATH=$PWD:$PATH KLOG=3 ./sh/gtest.sh

    - name: pytest
      run: |
        python3 setup.py pytest
