
name: Build Tick on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TICK_DEBUG: 0
  TICK_WERROR: 0

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: windows-2022
    timeout-minutes: 90

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
        python -m pip install pytest-timeout

    - name: build
      run: |
        python -m build --wheel

    - name: pytest
      env:
        PYTHONFAULTHANDLER: 1
      run: |
        python -m pytest -q --durations=50 --timeout=600
