name: Python packages Windows

on:
  release:
    types: [published]

env:
  TICK_DEBUG: 0
  TICK_WERROR: 0

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        pip install wheel twine pip --upgrade
        pip install -r requirements.txt
        python setup.py bdist_wheel

    - env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
