name: Python packages OSX

on:
  release:
    types: [published]

env:
  TICK_DEBUG: 0
  TICK_WERROR: 0

jobs:
  build:
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        brew update
        brew install automake m4
        git clone https://github.com/swig/swig -b rel-4.0.0 swig
        cd swig && ./autogen.sh && ./configure --without-pcre
        make && make install && cd .. && rm -rf swigkey

    - run: |
        pip install wheel twine pip --upgrade
        pip install -r requirements.txt
        python setup.py bdist_wheel

    - env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python3 -m twine upload dist/*
